// Authenticate
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_UPDATED_STATUS = 'SET_UPDATED_STATUS';

// GET DATA
export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';
export const GET_STUDENT_LIST_WITH_KEYWORD = 'GET_STUDENT_LIST_WITH_KEYWORD';
export const GET_JOB_LIST = 'GET_JOB_LIST';
export const GET_JOB_LIST_WITH_KEYWORD = 'GET_JOB_LIST_WITH_KEYWORD';
export const GET_SKILL_LIST = 'GET_SKILL_LIST';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';


// PUT DATA
export const PUT_STUDENT = 'PUT_STUDENT';


// MESSAGE
export const ON_REGISTER_SUCCESS = 'ON_REGISTER_SUCCESS';
export const ON_PUT_STUDENT_SUCCESS = 'ON_PUT_STUDENT_SUCCESS';
export const ON_PUT_RECRUITER_SUCCESS = 'ON_PUT_RECRUITER_SUCCESS';

//ON_PUT_RECRUITER_SUCCESS
export const POST_JOB_SUCCEED = 'POST_JOB_SUCCEED';
