// Authenticate
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// GET DATA
export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';
export const GET_JOB_LIST = 'GET_JOB_LIST';


// PUT DATA
export const PUT_STUDENT = 'PUT_STUDENT';


// MESSAGE
export const ON_REGISTER_SUCCESS = 'ON_REGISTER_SUCCESS';
export const ON_PUT_STUDENT_SUCCESS = 'ON_PUT_STUDENT_SUCCESS';
<<<<<<< HEAD
export const POST_JOB_SUCCEED = 'POST_JOB_SUCCEED';
=======
export const ON_PUT_RECRUITER_SUCCESS = 'ON_PUT_RECRUITER_SUCCESS';

//ON_PUT_RECRUITER_SUCCESS
>>>>>>> fbc19217b9c60c176ff83d8447597ec8231fc505
